"$schema" = 'https://starship.rs/config-schema.json'

format = """
$jobs\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$gleam\
$bun\
$golang\
$nodejs\
$shell\
"""

add_newline = false

[character]
success_symbol = '(bold white)'
error_symbol = '(bold red)'

[package]
disabled = true

[bun]
symbol = '🥟 '
detect_files = ['bun.lockb']

[nodejs]
symbol = "  "
detect_files = ['package.json', '.node-version', '!bunfig.toml', '!bun.lockb']
