"$schema" = 'https://starship.rs/config-schema.json'

format = """
$jobs\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$gleam\
$bun\
$nodejs\
$shell\
"""

add_newline = false

[username]
style_user = 'red bold'
style_root = 'black bold'
format = '[$user]($style) '
disabled = false
show_always = true


[character]
success_symbol = '(bold white)'
error_symbol = '(bold red)'

[package]
disabled = true

# [git_branch]
# symbol = ""
# format = '[git\([$branch](bold red)\)](bold blue) '

[bun]
symbol = '🥟 '
detect_files = ['bun.lockb']

[nodejs]
symbol = "  "
detect_files = ['package.json', '.node-version', '!bunfig.toml', '!bun.lockb']
