local opt = vim.opt

vim.g.mapleader = " "
vim.g.copilot_assume_mapped = true
vim.g.netrw_browse_split = 0
vim.g.netrw_banner = 0
vim.g.netrw_winsize = 25

opt.guicursor = ""
opt.nu = true
opt.nuw = 1
opt.relativenumber = true
opt.tabstop = 4
opt.softtabstop = 4
opt.shiftwidth = 4
opt.expandtab = true
opt.autoindent = true
opt.smartindent = true
opt.wrap = false
opt.hlsearch = false
opt.incsearch = true
opt.termguicolors = true
opt.cmdheight = 1
opt.scrolloff = 8
opt.signcolumn = "yes"
opt.updatetime = 50
opt.colorcolumn = "80"
opt.swapfile = false
opt.list = true
opt.listchars = "eol:↵"
